name: Render site
on: [push, pull_request]
jobs:
  Render-site:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements.txt"
      - run: mkdir -p build
      - name: render
        run: |
          python scripts/render_site.py
      - uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: main
          folder: build
          target-folder: docs
      - run: echo "🍏 This job's status is ${{ job.status }}."
